#!/usr/bin/env python3
# Copyright 2026 Baseten
# SPDX-License-Identifier: Apache-2.0

"""Generate the Cargo dependency and packaged-artifact license audit."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "THIRD_PARTY_LICENSES.md"
WORKSPACE_PACKAGES = {"basetenkenizer", "basetenkenizer-python"}
LICENSE_NAMES = {
    "copying",
    "license",
    "licence",
    "notice",
    "unlicense",
}


def cargo_metadata() -> dict:
    result = subprocess.run(
        ["cargo", "metadata", "--locked", "--format-version", "1"],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    return json.loads(result.stdout)


def shipped_package_ids(metadata: dict) -> set[str]:
    packages = {package["id"]: package for package in metadata["packages"]}
    nodes = {node["id"]: node for node in metadata["resolve"]["nodes"]}
    pending = [
        package_id
        for package_id, package in packages.items()
        if package["name"] in WORKSPACE_PACKAGES
    ]
    seen = set(pending)

    while pending:
        node = nodes[pending.pop()]
        for dependency in node["deps"]:
            kinds = dependency.get("dep_kinds") or [{"kind": None}]
            if not any(kind.get("kind") != "dev" for kind in kinds):
                continue
            package_id = dependency["pkg"]
            if package_id not in seen:
                seen.add(package_id)
                pending.append(package_id)

    return seen


def license_files(package: dict) -> list[Path]:
    directory = Path(package["manifest_path"]).parent
    paths = []
    for path in directory.iterdir():
        stem = path.name.lower().split(".", 1)[0].split("-", 1)[0]
        if path.is_file() and stem in LICENSE_NAMES:
            paths.append(path)
    return sorted(paths, key=lambda path: path.name.lower())


def render(metadata: dict) -> str:
    packages_by_id = {package["id"]: package for package in metadata["packages"]}
    package_ids = shipped_package_ids(metadata)
    packages = sorted(
        (
            packages_by_id[package_id]
            for package_id in package_ids
            if packages_by_id[package_id]["name"] not in WORKSPACE_PACKAGES
        ),
        key=lambda package: (package["name"].lower(), package["version"]),
    )

    texts: dict[str, tuple[str, str]] = {}
    package_text_ids: dict[str, list[str]] = {}
    missing_texts = []
    for package in packages:
        ids = []
        for path in license_files(package):
            try:
                content = path.read_text(encoding="utf-8").strip() + "\n"
            except UnicodeDecodeError:
                continue
            digest = hashlib.sha256(content.encode()).hexdigest()
            if digest not in texts:
                text_id = f"L{len(texts) + 1:03d}"
                texts[digest] = (text_id, content)
            ids.append(texts[digest][0])
        key = package["id"]
        package_text_ids[key] = sorted(set(ids))
        if not ids:
            missing_texts.append(f"{package['name']} {package['version']}")

    lines = [
        "# Third-party licenses and release audit",
        "",
        "> Generated by `scripts/generate_cargo_license_inventory.py` from",
        "> `Cargo.lock`. Do not edit this file manually.",
        "",
        "## Artifact scope",
        "",
        "- **Git source:** contains test-only and benchmarking materials governed by",
        "  separate upstream or file-level terms, including fixtures under",
        "  `vendored_tokenizers/` and files bundled from internal implementations.",
        "- **crates.io source package:** contains the Rust library source, this audit,",
        "  `LICENSE`, and `LICENSES/`; it excludes",
        "  `vendored_tokenizers/` and standalone files under `tests/`",
        "  as configured in `Cargo.toml`. Non-Apache test and benchmark materials are",
        "  also excluded from published crates.io and Python artifacts, including",
        "  files under `python/tests/`.",
        "- **Python wheels:** contain the Python package and a native extension built",
        "  from the normal/build Cargo dependency closure below. Vendored tokenizer",
        "  fixtures are not installed as wheel data.",
        "- **External Python requirements:** NumPy, and optional tiktoken, are resolved",
        "  and installed separately rather than copied into the wheel.",
        "- **Development-only dependencies:** excluded from this generated table",
        "  because they are not linked into release artifacts.",
        "",
        "License expressions are upstream Cargo metadata. An `OR` expression permits",
        "a distributor to select one listed license; this inventory does not record a",
        "legal election. The bundled texts below support auditing but do not replace",
        "review of upstream terms, copyright notices, or target-specific artifacts.",
        "",
        "## Derived and copied components",
        "",
        "- Portions derived from Crusoe's fastokens remain under Apache-2.0; see",
        "  `LICENSES/Apache-2.0.txt`.",
        "- Portions copied or adapted from gigatoken remain under MIT; see",
        "  `LICENSES/gigatoken-MIT.txt`.",
        "- The PCRE notice retained with the distribution is in",
        "  `LICENSES/PCRE-BSD.txt`.",
        "",
        "## Normal and build Cargo dependencies",
        "",
        "| Package | Version | Declared license | Bundled text IDs | Source |",
        "|---|---:|---|---|---|",
    ]

    for package in packages:
        source = package.get("source") or "workspace/path"
        ids = ", ".join(package_text_ids[package["id"]]) or "**missing**"
        lines.append(
            f"| `{package['name']}` | `{package['version']}` | "
            f"`{package.get('license') or 'UNKNOWN'}` | {ids} | `{source}` |"
        )

    lines.extend(["", "## Audit warnings", ""])
    if missing_texts:
        lines.append(
            "No top-level license text was found in the local Cargo source package for:"
        )
        lines.extend(f"- `{package}`" for package in missing_texts)
    else:
        lines.append("Every listed Cargo source package contained a discoverable license text.")

    lines.extend(["", "## Bundled license texts", ""])
    for text_id, content in sorted(texts.values()):
        lines.extend(
            [
                f"### {text_id}",
                "",
                "```text",
                content.rstrip(),
                "```",
                "",
            ]
        )

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when THIRD_PARTY_LICENSES.md is not current",
    )
    args = parser.parse_args()
    expected = render(cargo_metadata())

    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            print(
                "THIRD_PARTY_LICENSES.md is stale; run "
                "python3 scripts/generate_cargo_license_inventory.py",
                file=sys.stderr,
            )
            return 1
        return 0

    OUTPUT.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
